language: ruby

rvm:
- 2.3.3

branches:
  only:
  - blog

script: jekyll build

before_install:
 - openssl aes-256-cbc -K $encrypted_260bce340b80_key -iv $encrypted_260bce340b80_iv -in travis-key.enc -out ../travis-key -d
 - chmod 400 ../travis-key

after_success:
 - eval "$(ssh-agent -s)"
 - ssh-add ../travis-key
 - git clone git@github.com:33d/blog-pages.git target
 - cp -pr _site/* target
 - git -C target checkout -b gh-pages
 - git -C target add .
 - git -C target commit -m "$( date --utc --iso-8601=seconds )"
 - git -C target push --force origin gh-pages

sudo: false

