# Site settings
title: A blog
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: CommonMarkGhPages
permalink: /posts/:year/:month/:day/:title/

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 75
  sizes:
   - width: 400
  output: generated
  output_path_format: generated/%{width}-%{basename}
  save_to_source: false

disqus_shortname: dspblog

